name: Build VSFilterBE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clone DirectShow BaseClasses
      shell: pwsh
      run: |
        git clone https://github.com/ShiftMediaProject/DirectShowBaseClasses.git
        if (!(Test-Path "external/BaseClasses")) {
          New-Item -ItemType Directory -Path "external/BaseClasses" | Out-Null
        }
        Copy-Item "DirectShowBaseClasses/BaseClasses/*" "external/BaseClasses" -Recurse -Force

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build x86
      run: msbuild VSFilterBE.sln /p:Configuration=Release /p:Platform=x86

    - name: Build x64
      run: msbuild VSFilterBE.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VSFilterBE-Binaries
        path: |
          bin/Release/x86/VSFilterBE.dll
          bin/Release/x64/VSFilterBE.dll
